<?php

/**
 * @file
 * Gallery Views module help and theme functions.
 */

use Drupal\bootstrap_italia_views_gallery\Plugin\views\style\GalleryStyle;

/**
 * Implements hook_theme().
 *
 * @phpstan-return array{views_bootstrap_italia_views_gallery: array{variables: array{view: null, rows: null, options: null}}}
 */
function bootstrap_italia_views_gallery_style_theme(): array {
  return [
    'views_bootstrap_italia_views_gallery' => [
      'variables' => [
        'view' => NULL,
        'rows' => NULL,
        'options' => NULL,
      ],
    ],
  ];
}

/**
 * Prepares variables for bootstrap list templates.
 *
 * Default template: views-bootstrap-italia-views-gallery.html.twig.
 *
 * @phpstan-param array<string, mixed> $variables
 *   An associative array containing:
 *   - view: A ViewExecutable object.
 *   - rows: The raw row data.
 */
function template_preprocess_views_bootstrap_italia_views_gallery(array &$variables): void {
  // Update options for twig.
  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  $variables['options'] = $view->style_plugin->options;
}

/**
 * Implements hook_theme_suggestions_block_alter().
 *
 * @phpstan-param list<string> $suggestions
 * @phpstan-param array<string, mixed> $variables
 */
function bootstrap_italia_views_gallery_theme_suggestions_block_alter(array &$suggestions, array $variables): void {
  if (isset($variables['elements']['content']['#view'])) {
    $view = $variables['elements']['content']['#view'];

    // @todo This condition is always false?
    if ($view->style_plugin instanceof GalleryStyle) {
      $suggestions[] = 'block__views_views_bi_gallery__' . $view->id();
      $suggestions[] = 'block__views_views_bi_gallery';
    }
  }
}

/**
 * Implements hook_theme_suggestions_views_view_alter().
 *
 * @phpstan-param list<string> $suggestions
 * @phpstan-param array<string, mixed> $variables
 */
function bootstrap_italia_views_gallery_theme_suggestions_views_view_alter(array &$suggestions, array $variables): void {
  if ($variables['view']->style_plugin instanceof GalleryStyle) {
    $suggestions[] = $variables['theme_hook_original'] . '_bi_gallery__' . $variables['view']->storage->id();
    $suggestions[] = $variables['theme_hook_original'] . '_bi_gallery';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * @phpstan-param list<string> $suggestions
 * @phpstan-param array<string, mixed> $variables
 */
function bootstrap_italia_views_gallery_theme_suggestions_views_bootstrap_italia_views_gallery_alter(array &$suggestions, array $variables): void {
  if ($variables['view']->style_plugin instanceof GalleryStyle) {
    $suggestions[] = $variables['theme_hook_original'] . '_bi_gallery__' . $variables['view']->storage->id();
    $suggestions[] = $variables['theme_hook_original'] . '_bi_gallery';
  }
}
