<?php
/**
 * @file
 * The Bootstrap Italia Image Styles installation, Update and Uninstallation file.
 */

declare(strict_types = 1);

/**
 * Implements hook_install().
 * @param $is_syncing
 */
function bootstrap_italia_image_styles_install($is_syncing)
{
  // Set quality image
  Drupal::configFactory()
    ->getEditable('system.image.gd')
    ->set('jpeg_quality','100')
    ->save(TRUE);
}

/**
 * Implements hook_uninstall().
 * @param $is_syncing
 */
function bootstrap_italia_image_styles_uninstall($is_syncing)
{
  // Remove image styles configuration
  $image_style_installed = \Drupal::service('file_system')
    ->scanDirectory(__DIR__ . '/config/install/', ' /.+(yml)/', ['key' => 'name']);

  foreach ($image_style_installed as $key_image_style => $proprieties) {
    // image.style.image_style_machine_name_000x000
    Drupal::configFactory()->getEditable($key_image_style)->delete();
  }

  // Restore quality image to default value
  Drupal::configFactory()
    ->getEditable('system.image.gd')
    ->set('jpeg_quality','75')
    ->save(TRUE);
}

/**
 * Implements hook_update_N().
 * @param $sandbox
 */
function bootstrap_italia_image_styles_update_8001(&$sandbox)
{

}
