<?php

/**
 * @file
 * Theme file for Bootstrap Italia.
 */

// Include all files from the includes directory.
$includes_path = __DIR__ . '/includes/*.inc';

/**
 * All files in a path.
 *
 * @var list<string>|false $files
 */
$files = glob($includes_path);

/**
 * Name of a single file.
 *
 * @var string $filename
 */
foreach ((array) $files as $filename) {
  require_once __DIR__ . '/includes/' . basename($filename);
}
