<?php

/**
 * @file
 * The Bootstrap Italia Paragraphs, Update and Uninstallation file.
 */

declare(strict_types = 1);

/**
 * Implements hook_install().
 *
 * @param bool $is_syncing
 *   TRUE if the module is being installed as part of a configuration import.
 */
function bootstrap_italia_overlay_install($is_syncing) {

}

/**
 * Implements hook_uninstall().
 *
 * @param bool $is_syncing
 *   TRUE if the module is being uninstalled as part of a configuration import.
 */
function bootstrap_italia_overlay_uninstall($is_syncing) {

}

/**
 * Implements hook_update_N().
 *
 * @param array $sandbox
 *   Stores information for batch updates.
 */
function bootstrap_italia_overlay_update_8001(&$sandbox) {

}
