<?php
/**
 * @file
 * The Bootstrap Italia Paragraphs, Update and Uninstallation file.
 */

declare(strict_types = 1);

/**
 * Implements hook_install().
 * @param $is_syncing
 */
function bootstrap_italia_paragraphs_install($is_syncing)
{

}

/**
 * Implements hook_uninstall().
 * @param $is_syncing
 */
function bootstrap_italia_paragraphs_uninstall($is_syncing)
{

}

/**
 * Implements hook_update_N().
 * @param $sandbox
 */
function bootstrap_italia_paragraphs_update_8001(&$sandbox)
{

}
