italiagov.settings:
  type: theme_settings
  label: 'Italiagov settings'
  mapping:
    government_entity_name:
      type: label
      label: 'Government entity name'
      translatable: true
    government_entity_url:
      type: uri
      label: 'Government entity web site'
